### ISSUE TITLE
FragmentStatePager VS FragmentPager

### ISSUE THREAD

**Issue by ghost** [project-hipart/HiPart_ANDROID#10]
### 필요성
FragmentStatePager, FragmentPager 이해

### 내용
하단 탭을 편하게 구현하는 두 가지 예제의 차이를 알아보고

어떤 유형에서 사용해야할지 알아보자.

### 유형
논의

**Comment by vitriol2** [comment]
FragmentPager는 탭이 바뀌었을때 상태가 저장되구
FragmentStatePager는 항상 같은 모습을 유지한다아

탭 옮겼을 때 이전 탭의 수정이 있었을 경우 그 모습을 유지하고 싶다면 FragementPager!
유지할 필요가 없다면 FragmentStatePager~!

맞나여여어

**Comment by dlthgml1997** [comment]
FragmentPager 는 뷰의갯수가 정해져있을 때
FragmentStatePager는 뷰의 갯수가 정해져있지 않을 때 사용하는 것이 좋다
