### ISSUE TITLE
데이터 처리부 직렬화

### ISSUE THREAD

**Issue by ghost** [project-hipart/HiPart_ANDROID#11]
### 필요성
Retrofit에서 데이터를 받을 때 직렬화를 하는 이유를 알아보자.

### 내용
`implementation 'com.google.code.gson:gson:2.7'

```kotlin
class GithubAccessToken(
    @SerializedName("access_token") val accessToken: String,
    val scope: String,
    @SerializedName("token_type") val tokenType: String
)
```

위 코드의 `@SerializedName` 의 의미를 살펴보자.

### 유형
논의

**Comment by dlthgml1997** [comment]
<h2> @SerializedName </h2>
- GSON에서 사용되는 annotation이다. <br>
- @SerializedNamedml의 value는 객체를 직렬화 및 역직렬화 할 때 이름으로 사용된다.<br>
- tokenType 필드는 JSON에서 @SerializedName의 value의 값인 'token_type'으로 표출 된다.<br>

**Comment by vitriol2** [comment]
세미나에서 서버통신 배웠을 때는 
data class 를 사용하면서 저 어노테이션 사용을 안 했었는데
단순히 받아오는 json데이터와 코드안에서의 필드를 더 잘 매핑해준다는게 다인가??

**Comment by vitriol2** [comment]
아아아 json데이터에서의 이름이랑 코드에서 사용하는 필드명이 다를 때 변환시켜주는거 같애~!!
내말 잘 전달 됐을라나..

**Comment by dlthgml1997** [comment]
@vitriol2 오호 맞눈거 같애~!~!

**Comment by ghost** [comment]
ㅇㅇ 직렬화하는 주된 이유는 지원이가 말한게 맞아!

**Comment by ghost** [comment]
근데 데이터 처리부 직렬화의 주된 이유는 그건데 

데이터의 직렬화는 뭔지 알아보자!

**Comment by ghost** [comment]
내친구가 정리한건데 한번 슥 봐봐!

https://woovictory.github.io/2019/01/03/Android-What-is-serialization/
