### ISSUE TITLE
Context란?

### ISSUE THREAD

**Issue by ghost** [project-hipart/HiPart_ANDROID#12]
### 필요성
Context의 의미와 필요성을 깨닫자.

### 내용
Context는 뭐하는 놈인지 알아보자.

### 유형
논의

**Comment by dlthgml1997** [comment]
기능 시작함

**Comment by dlthgml1997** [comment]
어플리케이션의 리소스나 안드로이드 스튜디오의 자체 라이브러리를 사용할 때

**Comment by dlthgml1997** [comment]
1. 어플리케이션의 리소스 파일에 접근할 때 <br>2. 안드로이드 스튜디오 자체 라이브러리를 사용 할 때<br>3. 패키지명을 사용해야 할 때<br> ex) 리사이클러뷰에서 아이템 클릭 시 다른 액티비티로 이동할 때 Adapter에서 클릭리스너 함수 안에 startActivity 함수(원래 Adapter에서 사용 못하는 함수),\를 사용해야 할 때, Context를 매개변수로 받아서 사용할 수 있게 만든다
