### ISSUE TITLE
변수명 컨벤션

### ISSUE THREAD

**Issue by ghost** [project-hipart/HiPart_ANDROID#14]
### 필요성
변수명 규칙 정하기
### 내용
변수 혹은
xml 파일 이름 컨벤션 정하기
### 유형
논의

**Comment by dlthgml1997** [comment]
변수명 규칙 :: <b>기능_xml명_description(부가 설명)<br></b>
ex) et_login_act_id (activity_login.xml에 있는 id를 적는 EditText)
