### ISSUE TITLE
뷰 짜는 팁

### ISSUE THREAD

**Issue by ghost** [project-hipart/HiPart_ANDROID#15]
### 내용
8의 배수로 dp를 설정하는 이유

### 유형
(ex, 질문, 논의, 기능, 버그 픽스)

**Comment by vitriol2** [comment]
8은 행운의 숫자니까??

**Comment by ghost** [comment]
http://uidesignguides.com/8-point-%EA%B7%B8%EB%A6%AC%EB%93%9C%EB%A1%9C-%EB%94%94%EC%9E%90%EC%9D%B8%ED%95%98%EA%B8%B0/

**Comment by dlthgml1997** [comment]
주요 스크린의 사이즈가 8로 떨어지기 때문!

**Comment by ghost** [comment]
@dlthgml1997 아주 기가 맥히는 답안!
