### ISSUE TITLE
뷰 테두리 둥글게 만드는 간편한 방법

### ISSUE THREAD

**Issue by dlthgml1997** [project-hipart/HiPart_ANDROID#33]
### 필요성
뷰 테두리를 둥글게 만드는 간편한 방법은 무엇이 있을까요?

### 내용
android:ClipToPadding = "false" 를 추가하면 테두리가 약간 둥글게 됩니다!

### 유형
팁 공유

**Comment by cheongha** [comment]
감사합니당!

**Comment by ghost** [comment]
ImageVIew에 백그라운드에 동그란 xml파일(ex, border_box)을 추가한 뒤 

kt파일(Activity, Fragment) 등에서 `ImageView.clipToOutLine = true`를 사용할 수도 있어요
